### ISSUE TITLE
No audio support on Linux

### ISSUE THREAD

**Issue by monirz** [theinternetftw/dmgo#1]
Hello, I was trying your emulator after being able to compile it while I try to run >  dmgo <rom-name> 
I got an error like this `Platform AudioBuffer empty!` in the terminal. And there's no audio while game is running. What could be the problem, did you test this out? I'm on Linux. Thanks in advance.

**Comment by theinternetftw** [comment]
There's no audio support on linux.  The README specifically states "Audio (on windows)".

One thing I \*can\* do now is silence that debug message, since spamming the terminal isn't great.

And actually adding support is not completely off my radar (especially now that someone has asked for it).  I'll spin up a VM to take another look at it in the future.

**Comment by theinternetftw** [comment]
I've switched from windows hand-rolled sound to oto. This should now allow for linux audio, although libasound2-dev is a necessary C dependency and should be installed before compile.
